// Generated by internal/tools/facegen/facegen.py from the mood designs in
// internal/tools/facegen/design/svg/. Do not edit.

/// How long each mood design takes to play once through, in ms: its
/// longest animation, leaving out the blink, which the device times on
/// its own. A moment's `loops` count these, and the device's
/// firmware/assets/faces.h has the same numbers (PROTOCOL.md §3).
public enum FaceLoops {
    /// The designs' states, in `ms`'s order.
    public static let states = ["idle", "working", "needs_you", "task_complete", "asleep", "no_app"]

    /// By mood, each state's loop length, in `states`' order.
    public static let ms: [String: [Int64]] = [
        "happy": [9000, 2400, 1600, 2400, 8000, 8000],
        "excited": [9000, 1800, 1600, 2400, 8000, 8000],
        "proud": [9000, 7000, 1600, 2800, 8000, 8000],
        "curious": [9000, 5000, 1600, 2000, 8000, 8000],
        "determined": [9000, 2600, 1600, 2000, 8000, 8000],
        "grumpy": [9000, 4200, 1600, 2000, 8000, 8000],
        "sad": [9000, 6000, 6000, 6000, 8000, 8000],
    ]

    /// A design's loop length: `mood`'s design for `state`, happy's for a
    /// mood it doesn't know and idle's for a state it doesn't, as the
    /// device reads them.
    public static func ms(mood: String, state: String) -> Int64 {
        let row = ms[mood] ?? ms["happy"]!
        return row[states.firstIndex(of: state) ?? 0]
    }
}
