// Generated by internal/tools/facegen/facegen.py from the animation pack in
// internal/tools/facegen/design/. Do not edit.

/// How long each design takes to play once through, in ms: its longest
/// animation, leaving out the blink, which the device times on its own.
/// A moment's `loops` count these, and the device's firmware/assets/faces.h
/// has the same numbers (PROTOCOL.md §3).
public enum FaceLoops {
    /// The designs' states, in `ms`'s order.
    public static let states = ["idle", "working", "needs_you", "task_complete", "asleep", "no_app"]

    /// How many variations each state has, in `states`' order: a state's
    /// variations are numbered from 1.
    public static let variants = [3, 5, 3, 3, 3, 3]

    /// By mood, each state's loop lengths, one a variation, in `states`' order.
    public static let ms: [String: [[Int64]]] = [
        "happy": [[1000, 10000, 9000], [5000, 4000, 5000, 5000, 4000], [6000, 7200, 6400], [6400, 7200, 6400], [9000, 10000, 12000], [9000, 10000, 12000]],
        "excited": [[1000, 10000, 9000], [1600, 3000, 4000, 3600, 3000], [6000, 7200, 6400], [6400, 7200, 6400], [9000, 10000, 12000], [9000, 10000, 12000]],
        "proud": [[1000, 10000, 9000], [5000, 4000, 5000, 4500, 4000], [6000, 7200, 6400], [6400, 7200, 6400], [9000, 10000, 12000], [9000, 10000, 12000]],
        "curious": [[8000, 10000, 9000], [5000, 5000, 5000, 5000, 5000], [6000, 7200, 6400], [6400, 7200, 6400], [9000, 10000, 12000], [9000, 10000, 12000]],
        "determined": [[1000, 10000, 9000], [2400, 5000, 5000, 5000, 4000], [6000, 7200, 6400], [6400, 7200, 6400], [9000, 10000, 12000], [9000, 10000, 12000]],
        "grumpy": [[8000, 10000, 9000], [1800, 3200, 4400, 2700, 2400], [6000, 7200, 6400], [6400, 7200, 6400], [9000, 10000, 12000], [9000, 10000, 12000]],
        "sad": [[8000, 10000, 9000], [6400, 5000, 5000, 5000, 5000], [6000, 7200, 6400], [6400, 7200, 6400], [9000, 10000, 12000], [9000, 10000, 12000]],
    ]

    /// How many variations `state` has: 1 for a state it doesn't know.
    public static func count(state: String) -> Int {
        states.firstIndex(of: state).map { variants[$0] } ?? 1
    }

    /// A design's loop length: `mood`'s design for `state`, variation
    /// `variant` (from 1), as the device reads them: happy's for a mood it
    /// doesn't know, idle's for a state it doesn't, and the first
    /// variation for one out of range.
    public static func ms(mood: String, state: String, variant: Int = 1) -> Int64 {
        let row = ms[mood] ?? ms["happy"]!
        let loops = row[states.firstIndex(of: state) ?? 0]
        return loops[(1...loops.count).contains(variant) ? variant - 1 : 0]
    }

    /// The longest loop of any design.
    public static var longest: Int64 { ms.values.flatMap { $0.flatMap { $0 } }.max()! }
}
