// Boop's voice: the recorded takes on the board (plan/VOICE.md §3).
// Generated by internal/tools/voicegen/voicegen.py from internal/boop-design/assets/boop-voice-v1/.
// Don't edit; rerun the tool.

extension Take {
    /// Every take the board has, in the bank's order.
    public static let all: [Take] = [
        Take(id: "previous.go", text: "Go", meaning: "begin", kind: .word, mood: "calm", finish: nil, ms: 640),
        Take(id: "previous.work", text: "Work", meaning: "work", kind: .word, mood: "engaged", finish: nil, ms: 790),
        Take(id: "previous.finish", text: "Finish", meaning: "success", kind: .word, mood: "happy", finish: "success", ms: 1020),
        Take(id: "previous.done", text: "Done", meaning: "success", kind: .word, mood: "happy", finish: "success", ms: 690),
        Take(id: "previous.yay", text: "Yay", meaning: "celebrate", kind: .word, mood: "happy", finish: "success", ms: 960),
        Take(id: "previous.dai", text: "Dai", meaning: "begin", kind: .word, mood: "determined", finish: nil, ms: 460),
        Take(id: "previous.basta", text: "Basta", meaning: "frustration", kind: .word, mood: "annoyed", finish: nil, ms: 930),
        Take(id: "previous.aigo", text: "Aigo", meaning: "frustration", kind: .word, mood: "whiny", finish: nil, ms: 1240),
        Take(id: "previous.yatta", text: "Yatta", meaning: "celebrate", kind: .word, mood: "happy", finish: "success", ms: 1020),
        Take(id: "previous.oi", text: "Oi", meaning: "attention", kind: .word, mood: "curious", finish: nil, ms: 610),
        Take(id: "previous.eh", text: "Eh?", meaning: "ponder", kind: .sound, mood: "curious", finish: nil, ms: 580),
        Take(id: "previous.tsk", text: "Tsk...", meaning: "frustration", kind: .sound, mood: "annoyed", finish: nil, ms: 1370),
        Take(id: "previous.hrr", text: "Hrr...", meaning: "effort", kind: .sound, mood: "grumpy", finish: nil, ms: 1000),
        Take(id: "previous.pfft", text: "Pfft", meaning: "frustration", kind: .sound, mood: "annoyed", finish: nil, ms: 510),
        Take(id: "previous.krr", text: "Krr...", meaning: "effort", kind: .sound, mood: "whiny", finish: nil, ms: 1050),
        Take(id: "previous.rrtik", text: "Rrr... tik", meaning: "effort", kind: .sound, mood: "engaged", finish: nil, ms: 1920),
        Take(id: "previous.heh", text: "Heh...", meaning: "delight", kind: .sound, mood: "happy", finish: nil, ms: 961),
        Take(id: "previous.shit", text: "Shit", meaning: "frustration", kind: .swear, mood: "grumpy", finish: "failure", ms: 980),
        Take(id: "previous.fuck", text: "Fuck", meaning: "frustration", kind: .swear, mood: "grumpy", finish: "failure", ms: 950),
        Take(id: "previous.shiba", text: "Shiba", meaning: "frustration", kind: .swear, mood: "annoyed", finish: "failure", ms: 1010),
        Take(id: "new.d01", text: "Go", meaning: "begin", kind: .word, mood: "engaged", finish: nil, ms: 620),
        Take(id: "new.d02", text: "Go", meaning: "begin", kind: .word, mood: "excited", finish: nil, ms: 770),
        Take(id: "new.d03", text: "Done", meaning: "success", kind: .word, mood: "proud", finish: "success", ms: 1000),
        Take(id: "new.d04", text: "Done", meaning: "success", kind: .word, mood: "sad", finish: "success", ms: 750),
        Take(id: "new.d05", text: "Again", meaning: "retry", kind: .word, mood: "annoyed", finish: nil, ms: 1140),
        Take(id: "new.d06", text: "Again", meaning: "retry", kind: .word, mood: "irritated", finish: nil, ms: 1130),
        Take(id: "new.d07", text: "Again", meaning: "retry", kind: .word, mood: "whiny", finish: nil, ms: 1490),
        Take(id: "new.d08", text: "Again", meaning: "retry", kind: .word, mood: "determined", finish: nil, ms: 930),
        Take(id: "new.d09", text: "Hello", meaning: "attention", kind: .word, mood: "curious", finish: nil, ms: 760),
        Take(id: "new.d10", text: "Hello", meaning: "attention", kind: .word, mood: "calm", finish: nil, ms: 670),
        Take(id: "new.d11", text: "Hello", meaning: "attention", kind: .word, mood: "wounded", finish: nil, ms: 1000),
        Take(id: "new.d12", text: "Hrr...", meaning: "effort", kind: .sound, mood: "grumpy", finish: nil, ms: 900),
        Take(id: "new.d13", text: "Phew...", meaning: "relief", kind: .sound, mood: "happy", finish: "success", ms: 990),
        Take(id: "new.d14", text: "Mamma mia", meaning: "frustration", kind: .phrase, mood: "grumpy", finish: nil, ms: 1660),
        Take(id: "new.d15", text: "Bada bing bada boom", meaning: "celebrate", kind: .phrase, mood: "excited", finish: "success", ms: 1780),
        Take(id: "new.d16", text: "Tiny genius", meaning: "pride", kind: .phrase, mood: "proud", finish: "success", ms: 1890),
        Take(id: "new.d17", text: "Knock knock", meaning: "attention", kind: .phrase, mood: "curious", finish: nil, ms: 880),
        Take(id: "new.d18", text: "Aigo", meaning: "frustration", kind: .word, mood: "whiny", finish: nil, ms: 1500),
        Take(id: "new.d19", text: "Yatta", meaning: "celebrate", kind: .word, mood: "happy", finish: "success", ms: 1000),
        Take(id: "new.d20", text: "Mwahaha...", meaning: "delight", kind: .sound, mood: "proud", finish: nil, ms: 2430),
    ]
}
