#!/usr/bin/env python3
"""Generate a local XCTest-shim test runner.

When there is no full Xcode (only CommandLineTools), `swift test` links the
hand-written XCTest shim in TestSupport/XCTestShim, which has no runner — so
SwiftPM builds the tests but executes NONE of them and exits 0 (a false green).

This script parses Tests/*.swift for `XCTestCase` subclasses and their `test…`
methods, then emits Tests/GeneratedTestRunner.swift: an `@main` entry point
(guarded by `#if BOOP_SHIM_RUNNER`) that instantiates each case, runs
its setUp lifecycle, and invokes every test. `make test` regenerates this and
runs it via `swift run`, so the ~130 tests actually execute locally.

On CI (real Xcode / real XCTest) the Tests target stays a normal testTarget,
BOOP_SHIM_RUNNER is undefined, and this file compiles to nothing.

Idempotent: run it any time; it overwrites the generated file.
"""

from __future__ import annotations

import glob
import os
import re
import sys

TESTS_DIR = os.path.join(os.path.dirname(__file__), "..", "Tests")
OUT = os.path.join(TESTS_DIR, "GeneratedTestRunner.swift")

CLASS_RE = re.compile(r"^\s*(?:@\w+\s+)*(?:public\s+|final\s+|open\s+)*class\s+(\w+)\s*:\s*([^{]+)")
# zero-arg `func test…()` with optional async / throws, optionally @MainActor-prefixed
FUNC_RE = re.compile(r"^\s*(?:@\w+(?:\([^)]*\))?\s+)*func\s+(test\w+)\s*\(\s*\)\s*(async\s+)?(throws\s+)?")


def parse(path: str):
    """Yield (class_name, method_name, is_async, is_throws) in source order."""
    current = None  # name of the XCTestCase subclass we're inside, or None
    with open(path, encoding="utf-8") as f:
        for line in f:
            cm = CLASS_RE.match(line)
            if cm:
                name, conforms = cm.group(1), cm.group(2)
                current = name if re.search(r"\bXCTestCase\b", conforms) else None
                continue
            if current is None:
                continue
            fm = FUNC_RE.match(line)
            if fm:
                yield current, fm.group(1), bool(fm.group(2)), bool(fm.group(3))


def main() -> None:
    tests = []
    for path in sorted(glob.glob(os.path.join(TESTS_DIR, "*.swift"))):
        if os.path.basename(path) == "GeneratedTestRunner.swift":
            continue
        tests.extend(parse(path))

    if not tests:
        sys.exit("gen-test-runner: found no `test…` methods — refusing to write an empty runner")

    lines = [
        "// GENERATED by app/tools/gen-test-runner.py — do not edit by hand.",
        "// Runs the XCTest-shim tests locally when there is no full Xcode.",
        "#if BOOP_SHIM_RUNNER",
        "import Foundation",
        "import XCTest",
        "@testable import BoopCore",
        "",
        "@MainActor",
        "@main",
        "struct GeneratedTestRunner {",
        "    static func main() async {",
        "        var passed = 0, skipped = 0",
        "        func run(_ name: String, _ body: () async throws -> Void) async {",
        '            FileHandle.standardError.write("\\u{25B6} \\(name)\\n".data(using: .utf8)!)',
        "            do { try await body(); passed += 1 }",
        "            catch let e as XCTestShimError {",
        "                if case .skipped(let m) = e {",
        '                    skipped += 1; print("SKIP \\(name) — \\(m)")',
        "                } else {",
        '                    print("FAIL \\(name) — \\(e)"); exit(1)',
        "                }",
        "            }",
        '            catch { print("FAIL \\(name) — \\(error)"); exit(1) }',
        "        }",
        "",
    ]

    for cls, method, is_async, is_throws in tests:
        prefix = ("try " if is_throws else "") + ("await " if is_async else "")
        name = f"{cls}.{method}"
        lines.append(
            f'        await run("{name}") {{ '
            f"let t = {cls}(); do {{ try t.setUpWithError(); try await t.setUp(); "
            f"{prefix}t.{method}() }} catch {{ try await t.tearDown(); try t.tearDownWithError(); throw error }}; "
            f"try await t.tearDown(); try t.tearDownWithError() }}"
        )

    lines += [
        "",
        f"        let total = {len(tests)}",
        '        print("\\n\\u{2713} \\(passed) passed, \\(skipped) skipped of \\(total) tests")',
        "    }",
        "}",
        "#endif",
        "",
    ]

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"gen-test-runner: wrote {os.path.relpath(OUT)} ({len(tests)} tests)")


if __name__ == "__main__":
    main()
