"""Builds the device's two fonts (archived/plan-v1-build/PLAN.md F2) as C arrays.

Renders Geist Mono (SIL Open Font License 1.1, copyright Vercel) with
Pillow into 4-bit coverage cells: printable ASCII plus a middle dot. The
output, firmware/assets/fonts.h, is checked in; rerun this only to change
the fonts:

    internal/tools/.venv/bin/python internal/tools/fontgen/fontgen.py [--ttf-dir DIR]
"""
from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

REPO = Path(__file__).resolve().parents[3]
OUT = REPO / "firmware" / "assets" / "fonts.h"
# Where `npm ci` in landing/ puts Geist Mono.
TTF_DIR = REPO / "landing" / "node_modules" / "geist" / "dist" / "fonts" / "geist-mono"
# Drawn after '~' (0x7E), in this order; the renderer maps UTF-8 to them.
EXTRAS = ["·"]
# name, weight file, pixel size
FONTS = [("kFontSmall", "GeistMono-Medium.ttf", 13), ("kFontLarge", "GeistMono-SemiBold.ttf", 22)]


def render(name: str, path: Path, size: int) -> str:
    font = ImageFont.truetype(str(path), size)
    ascent, descent = font.getmetrics()
    w = round(font.getlength("M"))
    h = ascent + descent
    chars = [chr(c) for c in range(0x20, 0x7F)] + EXTRAS
    rowbytes = (w + 1) // 2
    data: list[int] = []
    for ch in chars:
        img = Image.new("L", (w, h), 0)
        ImageDraw.Draw(img).text((0, ascent), ch, fill=255, font=font, anchor="ls")
        px = img.load()
        for y in range(h):
            for bx in range(rowbytes):
                hi = px[2 * bx, y] * 15 // 255 if 2 * bx < w else 0
                lo = px[2 * bx + 1, y] * 15 // 255 if 2 * bx + 1 < w else 0
                data.append(hi << 4 | lo)
    lines = [f"// {path.name} at {size} px: {w}x{h} cells, baseline {ascent}, {len(chars)} glyphs."]
    lines.append(f"static const uint8_t {name}Data[{len(data)}] = {{")
    for i in range(0, len(data), 24):
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in data[i:i + 24]) + ",")
    lines.append("};")
    lines.append(f"constexpr Font {name} = {{{w}, {h}, {ascent}, {len(chars)}, {name}Data}};")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--ttf-dir", type=Path, default=TTF_DIR,
                        help="where Geist Mono's .ttf files are (default: landing/'s node_modules, after `npm ci`)")
    ttf_dir = parser.parse_args().ttf_dir
    if not (ttf_dir / FONTS[0][1]).exists():
        raise SystemExit(f"Geist Mono not found in {ttf_dir}; run `npm ci` in landing/ or pass --ttf-dir")
    body = "\n\n".join(render(n, ttf_dir / f, s) for n, f, s in FONTS)
    OUT.write_text(
        "// Generated by internal/tools/fontgen/fontgen.py. Do not edit.\n"
        "// Geist Mono, copyright 2023 Vercel, in collaboration with basement.studio,\n"
        "// under the SIL Open Font License 1.1 (firmware/assets/OFL.txt).\n"
        "// 4-bit coverage, two pixels per byte (high nibble first), row by row.\n"
        "#pragma once\n#include <cstdint>\n\n#include \"render/font.h\"\n\nnamespace render {\n\n"
        + body + "\n\n}  // namespace render\n"
    )
    print(f"wrote {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
