// GENERATED by app/tools/gen-test-runner.py — do not edit by hand.
// Runs the XCTest-shim tests locally when there is no full Xcode.
#if BOOP_SHIM_RUNNER
import Foundation
import XCTest
@testable import BoopCore

@MainActor
@main
struct GeneratedTestRunner {
    static func main() async {
        var passed = 0, skipped = 0
        func run(_ name: String, _ body: () async throws -> Void) async {
            FileHandle.standardError.write("\u{25B6} \(name)\n".data(using: .utf8)!)
            do { try await body(); passed += 1 }
            catch let e as XCTestShimError {
                if case .skipped(let m) = e {
                    skipped += 1; print("SKIP \(name) — \(m)")
                } else {
                    print("FAIL \(name) — \(e)"); exit(1)
                }
            }
            catch { print("FAIL \(name) — \(error)"); exit(1) }
        }

        await run("AutoApproveTests.testReadOnlyToolsAutoApprove") { let t = AutoApproveTests(); try t.setUpWithError(); try await t.setUp(); t.testReadOnlyToolsAutoApprove() }
        await run("AutoApproveTests.testNonCursorNeverAutoApproves") { let t = AutoApproveTests(); try t.setUpWithError(); try await t.setUp(); t.testNonCursorNeverAutoApproves() }
        await run("AutoApproveTests.testSafeSingleCommandsAutoApprove") { let t = AutoApproveTests(); try t.setUpWithError(); try await t.setUp(); t.testSafeSingleCommandsAutoApprove() }
        await run("AutoApproveTests.testChainedCommandIsNotAutoApproved") { let t = AutoApproveTests(); try t.setUpWithError(); try await t.setUp(); t.testChainedCommandIsNotAutoApproved() }
        await run("AutoApproveTests.testUnsafeCommandIsNotAutoApproved") { let t = AutoApproveTests(); try t.setUpWithError(); try await t.setUp(); t.testUnsafeCommandIsNotAutoApproved() }
        await run("AutoApproveTests.testStableCwdHashDoesNotUseRandomizedStringHash") { let t = AutoApproveTests(); try t.setUpWithError(); try await t.setUp(); t.testStableCwdHashDoesNotUseRandomizedStringHash() }
        await run("CopyRulesTests.testBuddyCopyFollowsBrandLaw") { let t = CopyRulesTests(); try t.setUpWithError(); try await t.setUp(); try t.testBuddyCopyFollowsBrandLaw() }
        await run("CopyRulesTests.testInlineViewTextLiteralRatchet") { let t = CopyRulesTests(); try t.setUpWithError(); try await t.setUp(); try t.testInlineViewTextLiteralRatchet() }
        await run("EngineIntegrationTests.testInitialStateIsDisconnectedSleeping") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testInitialStateIsDisconnectedSleeping() }
        await run("EngineIntegrationTests.testSessionStartConnects") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testSessionStartConnects() }
        await run("EngineIntegrationTests.testSessionEndDisconnects") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testSessionEndDisconnects() }
        await run("EngineIntegrationTests.testMultipleSessionsStayConnectedUntilAllEnd") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testMultipleSessionsStayConnectedUntilAllEnd() }
        await run("EngineIntegrationTests.testStartWorkingSetsBusy") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testStartWorkingSetsBusy() }
        await run("EngineIntegrationTests.testStopWorkingSetsIdle") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testStopWorkingSetsIdle() }
        await run("EngineIntegrationTests.testKeepWorkingMaintainsBusy") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testKeepWorkingMaintainsBusy() }
        await run("EngineIntegrationTests.testRequestArrivedSetsAttention") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testRequestArrivedSetsAttention() }
        await run("EngineIntegrationTests.testClearRequestReturnsToBusy") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testClearRequestReturnsToBusy() }
        await run("EngineIntegrationTests.testCelebrateSignalSetsCelebrate") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testCelebrateSignalSetsCelebrate() }
        await run("EngineIntegrationTests.testSessionCountsReflectActiveSessions") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testSessionCountsReflectActiveSessions() }
        await run("EngineIntegrationTests.testWaitingCountIncludesApprovals") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testWaitingCountIncludesApprovals() }
        await run("EngineIntegrationTests.testEndedSessionDecrementsCount") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testEndedSessionDecrementsCount() }
        await run("EngineIntegrationTests.testPromptShowsOldestWaitingRequest") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testPromptShowsOldestWaitingRequest() }
        await run("EngineIntegrationTests.testPromptClearsWhenNoWaitingSessions") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testPromptClearsWhenNoWaitingSessions() }
        await run("EngineIntegrationTests.testPromptShowsApprovalFields") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); await t.testPromptShowsApprovalFields() }
        await run("EngineIntegrationTests.testAttentionOverridesBusy") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testAttentionOverridesBusy() }
        await run("EngineIntegrationTests.testAttentionOverridesCelebrate") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testAttentionOverridesCelebrate() }
        await run("EngineIntegrationTests.testBusyOverridesCelebrate") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testBusyOverridesCelebrate() }
        await run("EngineIntegrationTests.testCelebrateExpiresAfterDuration") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testCelebrateExpiresAfterDuration() }
        await run("EngineIntegrationTests.testCelebrateStillActiveBeforeDuration") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testCelebrateStillActiveBeforeDuration() }
        await run("EngineIntegrationTests.testCelebrateRecordsTaskDuration") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testCelebrateRecordsTaskDuration() }
        await run("EngineIntegrationTests.testApprovalArrivedSetsAttention") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); await t.testApprovalArrivedSetsAttention() }
        await run("EngineIntegrationTests.testApprovalAllowResumesWorking") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); await t.testApprovalAllowResumesWorking() }
        await run("EngineIntegrationTests.testApprovalDenyGoesIdle") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); await t.testApprovalDenyGoesIdle() }
        await run("EngineIntegrationTests.testResolveAllPendingApprovals") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); await t.testResolveAllPendingApprovals() }
        await run("EngineIntegrationTests.testResolveAllPendingApprovalsCanPassthrough") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); await t.testResolveAllPendingApprovalsCanPassthrough() }
        await run("EngineIntegrationTests.testRemovedSessionWithPendingApprovalPassthroughs") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); await t.testRemovedSessionWithPendingApprovalPassthroughs() }
        await run("EngineIntegrationTests.testStaleReapResolvesPendingApprovalAsPassthrough") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); await t.testStaleReapResolvesPendingApprovalAsPassthrough() }
        await run("EngineIntegrationTests.testSetSpeciesUpdatesStateAndHeartbeat") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testSetSpeciesUpdatesStateAndHeartbeat() }
        await run("EngineIntegrationTests.testRecorderReceivesEveryStateChange") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testRecorderReceivesEveryStateChange() }
        await run("EngineIntegrationTests.testRecorderPrevMatchesPreviousNext") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testRecorderPrevMatchesPreviousNext() }
        await run("EngineIntegrationTests.testMultipleOutputsAllReceiveChanges") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testMultipleOutputsAllReceiveChanges() }
        await run("EngineIntegrationTests.testDesktopOutputPostsRapidAttentionTransitions") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testDesktopOutputPostsRapidAttentionTransitions() }
        await run("EngineIntegrationTests.testDuplicateSessionStartIsIdempotent") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testDuplicateSessionStartIsIdempotent() }
        await run("EngineIntegrationTests.testEndNonexistentSessionIsNoop") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testEndNonexistentSessionIsNoop() }
        await run("EngineIntegrationTests.testClearRequestWithoutPendingIsNoop") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testClearRequestWithoutPendingIsNoop() }
        await run("EngineIntegrationTests.testStaleTickRemovesExpiredSession") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testStaleTickRemovesExpiredSession() }
        await run("EngineIntegrationTests.testStaleTickKeepsFreshSession") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testStaleTickKeepsFreshSession() }
        await run("EngineIntegrationTests.testClaudePostToolUseThenStopRecordsLastCompletedToolName") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testClaudePostToolUseThenStopRecordsLastCompletedToolName() }
        await run("EngineIntegrationTests.testReviewSurvivesCelebrateWindowIntoIdleAndDismissClears") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testReviewSurvivesCelebrateWindowIntoIdleAndDismissClears() }
        await run("EngineIntegrationTests.testMultipleSessionsReviewReflectsCelebratingSessionTool") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testMultipleSessionsReviewReflectsCelebratingSessionTool() }
        await run("EngineIntegrationTests.testCursorStopSignalGoesThroughCelebratePath") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); t.testCursorStopSignalGoesThroughCelebratePath() }
        await run("EngineIntegrationTests.testHeartbeatIncludesLastCompletedFields") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); try t.testHeartbeatIncludesLastCompletedFields() }
        await run("EngineIntegrationTests.testHeartbeatIncludesEntriesArrayDuringBusy") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); try t.testHeartbeatIncludesEntriesArrayDuringBusy() }
        await run("EngineIntegrationTests.testBusyMsgRevertsToBlankWhenNoCurrentTool") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); try t.testBusyMsgRevertsToBlankWhenNoCurrentTool() }
        await run("EngineIntegrationTests.testBusyEntriesArrayCappedAt6OverWire") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); try t.testBusyEntriesArrayCappedAt6OverWire() }
        await run("EngineIntegrationTests.testHeartbeatPopulatesErrorToolFromErrorMsg") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); try t.testHeartbeatPopulatesErrorToolFromErrorMsg() }
        await run("EngineIntegrationTests.testHeartbeatErrorToolNilWhenNoTool") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); try t.testHeartbeatErrorToolNilWhenNoTool() }
        await run("EngineIntegrationTests.testHeartbeatActivityFieldReflectsCurrentToolKind") { let t = EngineIntegrationTests(); try t.setUpWithError(); try await t.setUp(); try t.testHeartbeatActivityFieldReflectsCurrentToolKind() }
        await run("HookInstallerTests.testUnreadableClaudeSettingsIsNotOverwritten") { let t = HookInstallerTests(); try t.setUpWithError(); try await t.setUp(); try t.testUnreadableClaudeSettingsIsNotOverwritten() }
        await run("HookInstallerTests.testClaudeInstallIsVerifiedAndIdempotent") { let t = HookInstallerTests(); try t.setUpWithError(); try await t.setUp(); try t.testClaudeInstallIsVerifiedAndIdempotent() }
        await run("HookInstallerTests.testUninstallUnreadableClaudeSettingsFailsWithoutChangingFile") { let t = HookInstallerTests(); try t.setUpWithError(); try await t.setUp(); try t.testUninstallUnreadableClaudeSettingsFailsWithoutChangingFile() }
        await run("HookInstallerTests.testUninstallClearsInstalledAgentsEntry") { let t = HookInstallerTests(); try t.setUpWithError(); try await t.setUp(); try t.testUninstallClearsInstalledAgentsEntry() }
        await run("HookInstallerTests.testDeletedScriptCorruptsAndRepairRestores") { let t = HookInstallerTests(); try t.setUpWithError(); try await t.setUp(); try t.testDeletedScriptCorruptsAndRepairRestores() }
        await run("HookInstallerTests.testCorruptBuddyConfigJSONHealthIsRepairable") { let t = HookInstallerTests(); try t.setUpWithError(); try await t.setUp(); try t.testCorruptBuddyConfigJSONHealthIsRepairable() }
        await run("HookInstallerTests.testOlderScriptVersionIsOutdatedAndRepairRestores") { let t = HookInstallerTests(); try t.setUpWithError(); try await t.setUp(); try t.testOlderScriptVersionIsOutdatedAndRepairRestores() }
        await run("HookInstallerTests.testCodexCommentedFeatureFlagDoesNotCountAsEnabled") { let t = HookInstallerTests(); try t.setUpWithError(); try await t.setUp(); try t.testCodexCommentedFeatureFlagDoesNotCountAsEnabled() }
        await run("HookInstallerTests.testCursorUsesManagedHelperAndRepairsMissingHelper") { let t = HookInstallerTests(); try t.setUpWithError(); try await t.setUp(); try t.testCursorUsesManagedHelperAndRepairsMissingHelper() }
        await run("HookServerBehaviorTests.testApprovalResponsePassthroughEncodings") { let t = HookServerBehaviorTests(); try t.setUpWithError(); try await t.setUp(); t.testApprovalResponsePassthroughEncodings() }
        await run("HookServerBehaviorTests.testApprovalResponseDecisionEncodings") { let t = HookServerBehaviorTests(); try t.setUpWithError(); try await t.setUp(); t.testApprovalResponseDecisionEncodings() }
        await run("HookServerBehaviorTests.testShouldAutoApproveBehavior") { let t = HookServerBehaviorTests(); try t.setUpWithError(); try await t.setUp(); t.testShouldAutoApproveBehavior() }
        await run("HookServerBehaviorTests.testPermissionPromptUsesLiveApprovalModeProvider") { let t = HookServerBehaviorTests(); try t.setUpWithError(); try await t.setUp(); try await t.testPermissionPromptUsesLiveApprovalModeProvider() }
        await run("PromptExpiryTests.testReducerClearsPromptOlderThanApprovalTimeout") { let t = PromptExpiryTests(); try t.setUpWithError(); try await t.setUp(); t.testReducerClearsPromptOlderThanApprovalTimeout() }
        await run("PromptExpiryTests.testReducerKeepsFreshPromptBeforeApprovalTimeout") { let t = PromptExpiryTests(); try t.setUpWithError(); try await t.setUp(); t.testReducerKeepsFreshPromptBeforeApprovalTimeout() }
        await run("PromptExpiryTests.testEngineResolvesPendingApprovalAsPassthroughWhenPromptExpires") { let t = PromptExpiryTests(); try t.setUpWithError(); try await t.setUp(); await t.testEngineResolvesPendingApprovalAsPassthroughWhenPromptExpires() }
        await run("ReducerTests.testInitialStateIsDisconnectedWithNoPrompt") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testInitialStateIsDisconnectedWithNoPrompt() }
        await run("ReducerTests.testSessionStartedBumpsVersion") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testSessionStartedBumpsVersion() }
        await run("ReducerTests.testRequestArrivedSetsPromptAndAttention") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testRequestArrivedSetsPromptAndAttention() }
        await run("ReducerTests.testRequestClearedRemovesPrompt") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testRequestClearedRemovesPrompt() }
        await run("ReducerTests.testSessionEndedRemovesSessionAndSleeps") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testSessionEndedRemovesSessionAndSleeps() }
        await run("ReducerTests.testStaleTickRemovesExpiredSessions") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testStaleTickRemovesExpiredSessions() }
        await run("ReducerTests.testVersionBumpsExactlyOncePerChange") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testVersionBumpsExactlyOncePerChange() }
        await run("ReducerTests.testMultipleSessionsTrackedIndependently") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testMultipleSessionsTrackedIndependently() }
        await run("ReducerTests.testAttentionPersistsWhenOtherSessionStops") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testAttentionPersistsWhenOtherSessionStops() }
        await run("ReducerTests.testBusyOverridesIdleAcrossSessions") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testBusyOverridesIdleAcrossSessions() }
        await run("ReducerTests.testCelebrateSignalSetsCelebrateState") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testCelebrateSignalSetsCelebrateState() }
        await run("ReducerTests.testCelebrateExpiresOnStaleTick") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testCelebrateExpiresOnStaleTick() }
        await run("ReducerTests.testAttentionOverridesCelebrate") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testAttentionOverridesCelebrate() }
        await run("ReducerTests.testBusyOverridesCelebrate") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testBusyOverridesCelebrate() }
        await run("ReducerTests.testShortTaskDurationBelowThreshold") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testShortTaskDurationBelowThreshold() }
        await run("ReducerTests.testLongTaskDurationAboveThreshold") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testLongTaskDurationAboveThreshold() }
        await run("ReducerTests.testCelebrateWithoutWorkStartHasNilDuration") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testCelebrateWithoutWorkStartHasNilDuration() }
        await run("ReducerTests.testMsgUsesDisplayedPromptSourceNotArbitrarySession") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testMsgUsesDisplayedPromptSourceNotArbitrarySession() }
        await run("ReducerTests.testMsgClearsWhenPromptResolves") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testMsgClearsWhenPromptResolves() }
        await run("ReducerTests.testApprovalPassthroughClearsPromptAndGoesIdle") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testApprovalPassthroughClearsPromptAndGoesIdle() }
        await run("ReducerTests.testDefaultSpeciesIsAKnownSpecies") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testDefaultSpeciesIsAKnownSpecies() }
        await run("ReducerTests.testSpeciesChangedUpdatesBuddyState") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testSpeciesChangedUpdatesBuddyState() }
        await run("ReducerTests.testKeepWorkingWithToolAndHintStashesOnSession") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testKeepWorkingWithToolAndHintStashesOnSession() }
        await run("ReducerTests.testCelebrateAfterKeepWorkingPopulatesLastCompletedWithCorrectTool") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testCelebrateAfterKeepWorkingPopulatesLastCompletedWithCorrectTool() }
        await run("ReducerTests.testLastCompletedPersistsAfterCelebrateWindowExpires") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testLastCompletedPersistsAfterCelebrateWindowExpires() }
        await run("ReducerTests.testLastCompletedClearsWhenNewRequestArrives") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testLastCompletedClearsWhenNewRequestArrives() }
        await run("ReducerTests.testLastCompletedClearsOnStartWorkingFromAnySession") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testLastCompletedClearsOnStartWorkingFromAnySession() }
        await run("ReducerTests.testReviewDismissedEventClearsLastCompleted") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testReviewDismissedEventClearsLastCompleted() }
        await run("ReducerTests.testIdleMsgShowsCompletionSummaryWhenLastCompletedSet") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testIdleMsgShowsCompletionSummaryWhenLastCompletedSet() }
        await run("ReducerTests.testBusyStateMsgIncludesCurrentToolFromPrimarySession") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testBusyStateMsgIncludesCurrentToolFromPrimarySession() }
        await run("ReducerTests.testCurrentToolClearsOnCelebrate") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testCurrentToolClearsOnCelebrate() }
        await run("ReducerTests.testCurrentToolClearsOnStopWorking") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testCurrentToolClearsOnStopWorking() }
        await run("ReducerTests.testMultipleWorkingSessionsMsgUsesOldestWorkStartedAt") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testMultipleWorkingSessionsMsgUsesOldestWorkStartedAt() }
        await run("ReducerTests.testEntriesAccumulateAndTruncateAt10") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testEntriesAccumulateAndTruncateAt10() }
        await run("ReducerTests.testKeepWorkingWithoutToolDoesNotOverwritePreviouslyStashedTool") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testKeepWorkingWithoutToolDoesNotOverwritePreviouslyStashedTool() }
        await run("ReducerTests.testErrorSignalSetsPetToErrorNotIdle") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testErrorSignalSetsPetToErrorNotIdle() }
        await run("ReducerTests.testStaleTickMarksSessionThinkingAfterStallTimeoutNoWorkSignal") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testStaleTickMarksSessionThinkingAfterStallTimeoutNoWorkSignal() }
        await run("ReducerTests.testStaleTickDoesNotMarkThinkingIfKeepWorkingWithinThreshold") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testStaleTickDoesNotMarkThinkingIfKeepWorkingWithinThreshold() }
        await run("ReducerTests.testThinkingSessionRecoversToWorkingOnKeepWorkingPreservingWorkStartedAt") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testThinkingSessionRecoversToWorkingOnKeepWorkingPreservingWorkStartedAt() }
        await run("ReducerTests.testErrorAndThinkingPriorityErrorWins") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testErrorAndThinkingPriorityErrorWins() }
        await run("ReducerTests.testBusyAndThinkingPriorityBusyWins") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testBusyAndThinkingPriorityBusyWins() }
        await run("ReducerTests.testThinkingMsgIncludesToolName") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testThinkingMsgIncludesToolName() }
        await run("ReducerTests.testErrorMsgUsesErrorPrefixNotStalled") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testErrorMsgUsesErrorPrefixNotStalled() }
        await run("ReducerTests.testErroredSessionRecoversToWorkingOnKeepWorking") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testErroredSessionRecoversToWorkingOnKeepWorking() }
        await run("ReducerTests.testErroredSessionWithActivePromptElsewherePetRemainsAttention") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testErroredSessionWithActivePromptElsewherePetRemainsAttention() }
        await run("ReducerTests.testDismissErrorClearsErroredStateForSession") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testDismissErrorClearsErroredStateForSession() }
        await run("ReducerTests.testFirstErroredHasOldestWorkStartedAtAcrossMultipleErrored") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testFirstErroredHasOldestWorkStartedAtAcrossMultipleErrored() }
        await run("ReducerTests.testActiveSessionsOrdersAttentionFirstThenErroredThenOldestWorking") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testActiveSessionsOrdersAttentionFirstThenErroredThenOldestWorking() }
        await run("ReducerTests.testActiveSessionsCappedAtSix") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testActiveSessionsCappedAtSix() }
        await run("ReducerTests.testActiveSessionsIncludesIdleSessionsAfterActiveOnes") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testActiveSessionsIncludesIdleSessionsAfterActiveOnes() }
        await run("ReducerTests.testActiveSessionsEmptyWhenNoSessions") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testActiveSessionsEmptyWhenNoSessions() }
        await run("ReducerTests.testIdenticalIdleSessionsKeepDistinctSnapshotIds") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testIdenticalIdleSessionsKeepDistinctSnapshotIds() }
        await run("ReducerTests.testActivityKindForSwiftTestCommandReturnsVerify") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testActivityKindForSwiftTestCommandReturnsVerify() }
        await run("ReducerTests.testActivityKindForGenericBashReturnsShell") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testActivityKindForGenericBashReturnsShell() }
        await run("ReducerTests.testActivityKindForReadToolReturnsRead") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testActivityKindForReadToolReturnsRead() }
        await run("ReducerTests.testActivityKindForEditToolReturnsWrite") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testActivityKindForEditToolReturnsWrite() }
        await run("ReducerTests.testActivityKindForWebToolReturnsWeb") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testActivityKindForWebToolReturnsWeb() }
        await run("ReducerTests.testActivityKindForUnknownToolReturnsWork") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testActivityKindForUnknownToolReturnsWork() }
        await run("ReducerTests.testPromptActivityKindSetAfterRequestArrived") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testPromptActivityKindSetAfterRequestArrived() }
        await run("ReducerTests.testSessionCurrentActivityKindSetAfterKeepWorking") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testSessionCurrentActivityKindSetAfterKeepWorking() }
        await run("ReducerTests.testCompletedTaskActivityKindCarriedOnCelebrate") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testCompletedTaskActivityKindCarriedOnCelebrate() }
        await run("ReducerTests.testBoopPutsIdlePetInHeart") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testBoopPutsIdlePetInHeart() }
        await run("ReducerTests.testBoopOverlaysBusyButKeepsMsg") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testBoopOverlaysBusyButKeepsMsg() }
        await run("ReducerTests.testBoopExpiresOnStaleTick") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testBoopExpiresOnStaleTick() }
        await run("ReducerTests.testBoopNeverOverridesAttention") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testBoopNeverOverridesAttention() }
        await run("ReducerTests.testBoopNeverOverridesError") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testBoopNeverOverridesError() }
        await run("ReducerTests.testBoopWhileAsleepStaysAsleep") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testBoopWhileAsleepStaysAsleep() }
        await run("ReducerTests.testAttentionArrivingDuringHeartWinsImmediately") { let t = ReducerTests(); try t.setUpWithError(); try await t.setUp(); t.testAttentionArrivingDuringHeartWinsImmediately() }
        await run("RequestIdTests.testFitsLegacyDeviceBufferForUUIDSession") { let t = RequestIdTests(); try t.setUpWithError(); try await t.setUp(); t.testFitsLegacyDeviceBufferForUUIDSession() }
        await run("RequestIdTests.testFitsForEveryPlausibleSessionShape") { let t = RequestIdTests(); try t.setUpWithError(); try await t.setUp(); t.testFitsForEveryPlausibleSessionShape() }
        await run("RequestIdTests.testIdsAreUniqueWithinOneSession") { let t = RequestIdTests(); try t.setUpWithError(); try await t.setUp(); t.testIdsAreUniqueWithinOneSession() }
        await run("RequestIdTests.testIdsStayDistinctAcrossSessionsAfterTruncation") { let t = RequestIdTests(); try t.setUpWithError(); try await t.setUp(); t.testIdsStayDistinctAcrossSessionsAfterTruncation() }
        await run("ResourceTests.testModuleBundleContainsFontAndSoundResources") { let t = ResourceTests(); try t.setUpWithError(); try await t.setUp(); t.testModuleBundleContainsFontAndSoundResources() }
        await run("ResourceTests.testGeistSemiBoldRegistersAndResolves") { let t = ResourceTests(); try t.setUpWithError(); try await t.setUp(); t.testGeistSemiBoldRegistersAndResolves() }
        await run("SnapshotHarnessTests.testSpeciesGallery") { let t = SnapshotHarnessTests(); try t.setUpWithError(); try await t.setUp(); try t.testSpeciesGallery() }
        await run("SnapshotHarnessTests.testPopoverSleep") { let t = SnapshotHarnessTests(); try t.setUpWithError(); try await t.setUp(); try t.testPopoverSleep() }
        await run("SnapshotHarnessTests.testPopoverBusy") { let t = SnapshotHarnessTests(); try t.setUpWithError(); try await t.setUp(); try t.testPopoverBusy() }
        await run("SnapshotHarnessTests.testPopoverPassivePrompt") { let t = SnapshotHarnessTests(); try t.setUpWithError(); try await t.setUp(); try t.testPopoverPassivePrompt() }
        await run("SnapshotHarnessTests.testApprovalButtonLoop") { let t = SnapshotHarnessTests(); try t.setUpWithError(); try await t.setUp(); try await t.testApprovalButtonLoop() }
        await run("SnapshotHarnessTests.testSettings") { let t = SnapshotHarnessTests(); try t.setUpWithError(); try await t.setUp(); try t.testSettings() }
        await run("SnapshotHarnessTests.testOnboardingSteps") { let t = SnapshotHarnessTests(); try t.setUpWithError(); try await t.setUp(); try t.testOnboardingSteps() }

        let total = 155
        print("\n\u{2713} \(passed) passed, \(skipped) skipped of \(total) tests")
    }
}
#endif
