// Six new characters. No mood aliases and no externally selected intensity.
export const newMoods=['calm','engaged','annoyed','irritated','whiny','wounded'];
export const moodProfiles={
 calm:{pace:1.22,gain:.48,pitch:.98,knocks:[.55,1.24],tapGain:.27,character:'Settled, big-eyed and unhurried; small precise motions, soft content breaths.'},
 engaged:{pace:.94,gain:.62,pitch:1.02,knocks:[.42,.73,1.11],tapGain:.46,character:'Alert eyes track the next step; compact confident flow, no straining or anger.'},
 annoyed:{pace:1.10,gain:.56,pitch:.96,knocks:[.50,1.14,1.40],tapGain:.44,character:'Held side-eye, compressed mouth, reluctant corrections and a long dry pause.'},
 irritated:{pace:.83,gain:.65,pitch:.98,knocks:[.32,.49,.81,.98],tapGain:.65,character:'Twitching eye, uneven clipped motions and quick corrective jabs; not full grumpy destruction.'},
 whiny:{pace:1.16,gain:.48,pitch:1.05,knocks:[.62,1.19,1.48],tapGain:.28,character:'Baby pout, watery eyes and cube tears while still doing the work; an active plea for sympathy.'},
 wounded:{pace:1.30,gain:.40,pitch:.98,knocks:[.76,1.60],tapGain:.20,character:'Glassy eyes, inward flinch, hesitant approach then retreat; quietly checking if you still care.'}
};
// Different props and actions, not renamed timings of one performance.
export const workActions={
 calm:[['flow-keys','Unhurried flow','A short typing phrase, a breath, then a careful final key.'],['tea-desk','Tea beside the task','Set down a steaming block cup; type a small phrase beside it.'],['file-garden','Tidy little garden','Plant three work tiles into orderly slots, then close the tray.'],['polish-row','A clean workspace','Sweep square dust into a pan; straighten the workstation.'],['paper-fold','Fold and file','Fold a sheet into a little packet and tuck it into a folder.']],
 engaged:[['split-keys','Two-track flow','Alternate between two compact keyboards and bring the results together.'],['card-sort','Sort the incoming work','Catch sliding cards and distribute them into three trays.'],['cube-belt','Keep the belt moving','Feed blocks along a belt into a slot, without claiming the task is complete.'],['cable-knit','Connect the pieces','Seat three chunky plugs into their matching sockets.'],['blueprint','Build from the plan','Unroll a blueprint, align its blocks and roll it up again.']],
 annoyed:[['reluctant-key','Fine, one more key','Pause in a side-eye, reach reluctantly, then press one oversized key.'],['crooked-stack','Stay. Straight.','Straighten a leaning stack; it tilts again, earning a dry side-eye.'],['stuck-drawer','Not this drawer again','Pull a sticking file drawer twice before easing it open.'],['pencil-flick','The pencil protest','Set a pencil down, flick it away, then retrieve it to keep working.'],['erase-again','Rub it out, again','Erase one line in broad strokes; push the square crumbs aside.']],
 irritated:[['repeat-enter','Enter, enter, ENTER','Three accelerating oversized Enter-key jabs and a clipped recoil.'],['cable-tug','The cable is tangled','Tug a chunky cable, recoil, untangle it and plug it in.'],['jammed-feed','Paper, please move','A paper feed jams; two corrections free the accordion sheet.'],['ratchet-kick','Stubborn little gear','Crank a resistant gear in short bursts; square dust shakes loose.'],['red-pencil','No, this bit','Rapidly mark, cross out and correct a page with a chunky red pencil.']],
 whiny:[['tear-type','Typing through a complaint','Continue typing while two lanes of blue cube tears splash beside the keys.'],['tissue-type','One paw for the tears','Pull a long tissue with one pad; keep typing with the other.'],['drag-stack','But it is so heavy','Drag a tall stack across the desk, pause to pout, then pull again.'],['pout-crank','Whimper and wind','Work a large crank through a drooping pout; tiny tear cubes bounce off it.'],['umbrella-work','A very small shelter','Open a tiny umbrella over the keyboard, then type beneath falling tear cubes.']],
 wounded:[['cautious-key','Careful little keystrokes','Approach the keyboard, flinch back, then try a softer short phrase.'],['patch-paper','Mend the little tear','Line up a torn page and smooth a square patch over it.'],['shield-desk','A sheltered desk','Raise a protective desk panel and keep working behind it.'],['peek-folder','Peek and continue','Hide briefly behind a folder, peek over it and carefully resume.'],['collect-pieces','Still picking up the pieces','Gather scattered work tiles into a small box and hold it close.']]
};
// Shared semantic actions, each performed with its own new-mood face and kinetics.
const definitions={
 no_app:[['doze','Disconnected doze','Closed eyes breathe beside an unconnected plug.'],['plug-rest','Plug at rest','Nudge the loose plug, then settle; no fake reconnection.'],['blanket','Waiting under a blanket','A small folded cover rises and settles over the resting face.']],
 asleep:[['breathe','Sleepy breathing','Quiet shared closed eyes, barely rising and settling.'],['dream','One dream square','A single dream block drifts up and disappears.'],['resettle','Pillow resettle','A broad pillow shifts; Boop settles back into the same pose.']],
 idle:[['blink','A moment to breathe','A readable mood face and one small blink.'],['look','Look left, look right','Glance around and return to center without inventing work.'],['stretch','Little stretch','Two soft pads stretch outward, then tuck away.']],
 listening:[['focus','I am listening','Broad corner brackets quietly settle around the face.'],['headset','Headset on','A blocky headset drops onto the head and gently lifts away.'],['trumpet','All ears','Lean toward a large simple listening trumpet.']],
 starting:[['placard','The opening card','Raise a factual start card and unfold the desk.'],['ticket','Task ticket','Pull a start ticket from a small printer, read it, then file it.'],['shutter','Open for work','Roll a little desk shutter up to reveal the start label.']],
 planning:[['route','A route in blocks','Arrange three numbered step cards into a zigzag route.'],['blueprint','Roll out the plan','Unroll a large plan, point to three areas, then roll it closed.'],['board','Rearrange the board','Move a middle note between three planning columns.']],
 terminal:[['matrix','Binary rain','Type below falling green block-code and binary columns.'],['console','Open the console','Unfold a terminal window; a chunky cursor advances along toy code.'],['code-reel','The code reel','Crank a narrow ribbon of toy code through a reader.']],
 tool_use:[['toolbox','Pick the right tool','Open a toolbox, choose a broad wrench, seat it, put it back.'],['socket','Make the connection','Bring a large plug across the screen and connect its socket.'],['gear','Turn the mechanism','Mesh two gears and work the large lever.']],
 searching:[['globe','Look around the world','Sweep a magnifier across a globe and send a query tile.'],['radar','Sweep for sources','A stepped radar sweep catches three source squares.'],['telescope','A long look','Extend a toy telescope, scan, then collect a source card.']],
 analyzing:[['compare','Compare the evidence','Hold two different pages, alternate scrutiny, then group them.'],['lens','Under the big lens','Move a magnifier over an enlarged page and reveal its block pattern.'],['sort','Clues into piles','Sort patterned source tiles into three evidence trays.']],
 testing:[['gate','Inspection gate','Feed sample cubes under an amber scanner; no invented result.'],['bench','Test bench','Press a test lever and inspect three unfilled result slots.'],['tiles','Test-case carousel','Rotate three sample tiles through a magnifier; no pass checkmark.']],
 delegating:[['hatch','Helpers from the hatch','Three little robots emerge with work parcels and move out.'],['squad','Squad, move out','A rounded-pad salute, a GO card and a small robot formation.'],['chutes','Work parcel launch','Send three work cubes down separate chutes to waiting helper robots.']],
 helper_return:[['courier','A report arrives','A tiny robot carries a report across the desk and hands it over.'],['salute','Reporting back','Helpers line up, salute with simple pads and present REPORT.'],['mailbox','Helper post','A mailbox flag rises; Boop takes a report envelope from the hatch.']],
 waiting:[['hourglass','Waiting, still here','A broad hourglass drops square grains, then turns.'],['chair','A patient seat','Lean on a small stool and gently shift position.'],['pendulum','Watching time','Track a quiet chunky pendulum; no numeric progress promise.']],
 needs_you:[['tap-panel','Knock and ask','Broad mood-shaped taps; the signature ding reveals a large ASK panel.'],['card-knock','The request card','Use a large request card to tap the screen, then reveal the alert.'],['bell-pull','Ring for you','Tap different areas, then pull a cord to reveal a broad block bell.']],
 reply_ready:[['tray','An answer on a tray','Open an answer sheet and slide the tray toward the user.'],['scroll','Unroll the answer','Unroll a wide answer scroll and hold it open.'],['envelope','An answer envelope','Present a large open envelope with an ANSWER card inside.']],
 task_complete:[['cup','Trophy lift','Raise a cup and COMPLETE card amid square fireworks.'],['ribbon','The completion rosette','Unfurl a broad rosette and COMPLETE ribbon.'],['podium','Onto the podium','Rise on a stepped podium, hold COMPLETE and celebrate.']],
 error:[['jam','A tool jam','A mechanism sticks and sheds a few square fragments; ERROR, not task over.'],['cable','Disconnected tool','A tool cable pops out; catch it and show ERROR.'],['page','The error slip','An ERROR slip emerges from a reluctant printer.']],
 stopped:[['brake','Tools down','Brake a moving belt; loose blocks settle under STOPPED.'],['lid','Close the workstation','Fold the keyboard into a case and lower the lid.'],['flag','Pause the production line','Plant a STOPPED flag; the work cart gently rolls to a halt.']],
 poked:[['squash','Squash and rebound','A broad soft contact squashes the face; it returns a mood-shaped look.'],['peek','Peek at the tap','Lean toward a side contact, inspect it, then draw back.'],['high-pad','A soft hello','Offer one large simple pad, make contact and tuck it away.']],
 tap_spam:[['shield','Easy, easy','Duck behind a large cushioned EASY shield as contacts arrive from both sides.'],['duck','Over here? Over there?','Dodge three broad contact patches, then look out from a low crouch.'],['curtain','A little privacy','Pull a small curtain across, peek out, then open it again.']]
};
const failure=[['fallen-tower','The work did not hold','A work tower splits into pieces; hold FAILED, no celebration.'],['torn-result','A broken result','A result sheet tears into two halves; present FAILED.'],['empty-podium','No trophy this time','An empty result stand lowers; a large FAILED card replaces it.']];
const durations={working:[5.4,6.2,5.8,6.7,5.6],starting:[5.4,6.2,5.8],needs_you:[5.6,6.2,6.7],task_complete:[6.4,6.8,7.2],terminal:[5.4,6.2,6.6],asleep:[9,10,12],no_app:[9,10,12],idle:[8,10,9],waiting:[7,8,9]};
export const moodAdditions=newMoods.flatMap(mood=>Object.entries(definitions).flatMap(([state,defs])=>{
 const entries=state==='starting'?['new_task','session','continuation'].flatMap(startContext=>defs.map(d=>({d,startContext}))):state==='task_complete'?[...defs.map(d=>({d,outcome:'success'})),...failure.map(d=>({d,outcome:'failure'}))]:defs.map(d=>({d}));
 return entries.map(({d,startContext,outcome},i)=>make(mood,state,d,i+1,{...(startContext?{startContext}:{}),...(outcome?{outcome}:{})}));
}).concat(workActions[mood].map((d,i)=>make(mood,'working',d,i+1))));
function make(mood,state,[action,name,caption],variation,extra={}){
 const quiet=['asleep','no_app'].includes(state),pace=quiet||state==='task_complete'?1:moodProfiles[mood].pace;
 const seconds=Number(((durations[state]||[5.3,6.1,5.7])[(variation-1)%3]*pace+(state==='working'&&variation>3?.4:0)).toFixed(3));
 return {id:`${mood}.${state}.${String(variation).padStart(2,'0')}`,mood,state,variation,action,name,caption,seconds,renderer:'mood-v4',approval:'Review candidate',sharedQuiet:quiet,...extra};
}
